[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@ensdomains/buffer/=lib/buffer"]
fs_permissions = [{access = "read", path = "./script/premint/"}]

[rpc_endpoints]
iliad="${IP_ILIAD_URL}"
base-sepolia="${BASE_SEPOLIA_RPC_URL}"

