[profile.default]
src = "src"
out = "out"
gas-price-cap = "3.00 ether" 
libs = ["lib"]
remappings = ["@ensdomains/buffer/=lib/buffer"]
fs_permissions = [{access = "read", path = "./script/premint/"}]

[rpc_endpoints]
iliad="${IP_ILIAD_URL}"
odyssey="${ODYSSEY_RPC_URL}"

